### ISSUE TITLE
dng_demo error

### ISSUE THREAD

**Issue by montyhall** [j-wilson/bot7#22]
Line 144 of `dng_demo` at https://github.com/j-wilson/bot7/blob/master/examples/dngo_demo.lua should be `opt.nTrain` not `opt.nTest`

**Comment by j-wilson** [comment]
Yup, you're totally right. I'm a touch busy at the moment; but, will
address this issue when I free up. Alternatively, you're welcome to submit
an pull request if you'd like.


-- james
